/**
 * The tool registry — the single source of truth for this server's surface.
 *
 * `surface.json` is generated by introspecting this array, so the parity gate
 * in nimbioCore can tell when the API grows an operation no tool exposes.
 * Order is deliberate and stable: the spec asks for a deterministic tool list
 * so clients can cache it.
 */
import type { ToolDef } from "./types.js";
import { whoami, communityOverview, gateStatus } from "./identity.js";

export const TOOLS: readonly ToolDef[] = Object.freeze([
  whoami,
  communityOverview,
  gateStatus,
]);

export type { ToolDef } from "./types.js";
