/**
 * The tool registry — the single source of truth for this server's surface.
 *
 * `surface.json` is generated by introspecting this array, so nimbioCore's
 * parity gate can tell when the API grows an operation no tool exposes.
 *
 * Order is deliberate and stable: the spec asks for a deterministic tool list
 * so clients can cache it and prompt caches stay warm. Tools are grouped the
 * way a manager thinks — orient, look at gates, look at people, guests, logs,
 * config, plumbing — not the way the REST paths are grouped.
 */
import type { ToolDef } from "./types.js";
import { whoami, communityOverview, gateStatus } from "./identity.js";
import { listGates, keyStatuses, holdOpens } from "./gates.js";
import { listMembers, keySchedule, communityKeys } from "./members.js";
import { listGuestLinks, listAccessCodes, guestViewEntry, shortCodes } from "./guests.js";
import { accessLog, gateStatusLog, changeLog, keyUsage } from "./logs.js";
import { settings, homes, senseLines, nfcTags } from "./config.js";
import { webhooks, webhookDeliveries, messages, myNotificationSettings } from "./webhooks.js";
import { myKeys } from "./account.js";

export const TOOLS: readonly ToolDef[] = Object.freeze([
  // Orientation
  whoami,
  communityOverview,
  // Gates
  listGates,
  gateStatus,
  keyStatuses,
  holdOpens,
  // People and their access
  listMembers,
  communityKeys,
  keySchedule,
  // Guests
  listGuestLinks,
  listAccessCodes,
  guestViewEntry,
  shortCodes,
  // Audit
  accessLog,
  gateStatusLog,
  changeLog,
  keyUsage,
  // Configuration and hardware
  settings,
  homes,
  senseLines,
  nfcTags,
  // Plumbing
  webhooks,
  webhookDeliveries,
  messages,
  myNotificationSettings,
  // Account scope
  myKeys,
]);

export type { ToolDef } from "./types.js";
